### ISSUE TITLE
Consistency in switches (Develop)

### ISSUE THREAD

**Issue by samhunter** [dstreett/Super-Deduper#28]
A number of discrepancies exist between master and develop for capitalization of switches. Wherever possible it would be nice to keep these consistent to avoid breakage of scripts etc across version.

I have tried to list all of the mismatches here, (these are listed Master branch : Develop branch)
-i : -I 
-p : -P 
-V : -v  (I prefer the lower case option personally)

**Comment by dstreett** [comment]
I want -I to keep with that, since it is -U, -1, -2 it seems input should be capital. However, that is a pretty weak excuse. 

-p versus -P I really don't care, we can keep it -p.

-V was put in by some dumb undergrad. I think -v is much more common and it should be switched.

I think -v should be changed, the other two, I don't care. What are your thoughts, @samhunter

**Comment by samhunter** [comment]
Yeah, -I makes sense. 

How about:
-I
-p
-v

**Comment by dstreett** [comment]
Changed -P to -p.
